
import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import{getFirestore,doc,setDoc,getDoc,updateDoc,increment,arrayUnion}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyAI31IV5RMxCLs5DiBaYjFVcHUFW5KDIeQ",authDomain:"ayniyiz-1a512.firebaseapp.com",projectId:"ayniyiz-1a512",storageBucket:"ayniyiz-1a512.firebasestorage.app",messagingSenderId:"926954313338",appId:"1:926954313338:web:006c9d26e7b8dae9860dc3",measurementId:"G-J6WPPNT26E"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);await setPersistence(auth,browserLocalPersistence);window.currentUser=null;window.pendingResult=null;
function renderLoggedOut(){const box=document.getElementById("userBox");if(box)box.innerHTML=`<input type="email" id="email" placeholder="E-mail"><input type="password" id="password" placeholder="Şifre"><button onclick="loginUser()">Giriş Yap</button><button onclick="registerUser()">Kayıt Ol</button>`;document.querySelectorAll(".creditBadge").forEach(b=>b.innerText="⚡ Giriş yap")}
function renderLoggedIn(user,credits="..."){const box=document.getElementById("userBox");if(box)box.innerHTML=`<div class="creditBadge">⚡ Kredin: ${credits}</div><div class="userEmail">${user.email}</div><button onclick="logoutUser()">Çıkış Yap</button>`}
async function ensureUserDoc(user){const ref=doc(db,"users",user.uid),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{email:user.email,credits:4,welcomeCreditsGiven:true,createdAt:new Date().toISOString(),solvedTests:[]},{merge:true});return 4}const data=snap.data();if(data.credits===undefined){await updateDoc(ref,{credits:4,welcomeCreditsGiven:true});return 4}return data.credits||0}
window.refreshCredits=async()=>{if(!window.currentUser)return;try{const snap=await getDoc(doc(db,"users",window.currentUser.uid));const credits=snap.exists()?(snap.data().credits||0):0;document.querySelectorAll(".creditBadge").forEach(b=>b.innerText="⚡ Kredin: "+credits)}catch(e){document.querySelectorAll(".creditBadge").forEach(b=>b.innerText="⚡ Kredin: ?")}}
window.registerUser=async()=>{const email=document.getElementById("email")?.value||document.getElementById("modalEmail")?.value,password=document.getElementById("password")?.value||document.getElementById("modalPassword")?.value;if(!email||!password)return alert("E-mail ve şifre gir.");try{const u=await createUserWithEmailAndPassword(auth,email,password);window.currentUser=u.user;renderLoggedIn(u.user,"4");await ensureUserDoc(u.user);await refreshCredits();alert("Kayıt başarılı ⚡ 4 kredi hesabına tanımlandı.");closeAuthModal();if(window.pendingResult){await window.saveQuizResult(window.pendingResult);window.pendingResult=null}}catch(e){alert(e.message)}}
window.loginUser=async()=>{const email=document.getElementById("email")?.value||document.getElementById("modalEmail")?.value,password=document.getElementById("password")?.value||document.getElementById("modalPassword")?.value;if(!email||!password)return alert("E-mail ve şifre gir.");try{const u=await signInWithEmailAndPassword(auth,email,password);window.currentUser=u.user;renderLoggedIn(u.user,"...");await ensureUserDoc(u.user);await refreshCredits();alert("Giriş başarılı ⚡");closeAuthModal();if(window.pendingResult){await window.saveQuizResult(window.pendingResult);window.pendingResult=null}}catch(e){alert(e.message)}}
window.logoutUser=async()=>{await signOut(auth);window.currentUser=null;renderLoggedOut()}
window.openAuthModal=()=>document.getElementById("authModal")?.classList.add("show");window.closeAuthModal=()=>document.getElementById("authModal")?.classList.remove("show");
window.addCredits=async(amount)=>{if(!window.currentUser){openAuthModal();return}await updateDoc(doc(db,"users",window.currentUser.uid),{credits:increment(amount)});await refreshCredits()}
window.buyCredits=async(amount,price)=>{const ok=confirm(amount+" kredi / "+price+" TL paketini almak istiyor musun?");if(!ok)return;await addCredits(amount);alert(amount+" kredi hesabına eklendi ⚡")}
window.useCreditForTest=async()=>{if(!window.currentUser){openAuthModal();return false}const ref=doc(db,"users",window.currentUser.uid),snap=await getDoc(ref),credits=snap.exists()?(snap.data().credits||0):0;if(credits<1){alert("Yeterli kredin yok. Kredi yükleme sayfasına yönlendiriliyorsun.");location.href="kredi.html";return false}await updateDoc(ref,{credits:increment(-1)});await refreshCredits();return true}
window.saveQuizResult=async(payload)=>{const user=auth.currentUser;if(!user){window.pendingResult=payload;openAuthModal();return}try{await updateDoc(doc(db,"users",user.uid),{solvedTests:arrayUnion(payload)});alert("Sonucun kaydedildi ⚡")}catch(e){alert("Sonuç kaydedilemedi: "+e.message)}}
onAuthStateChanged(auth,async user=>{window.currentUser=user;if(!user){renderLoggedOut();return}renderLoggedIn(user,"...");try{await ensureUserDoc(user);await refreshCredits()}catch(e){document.querySelectorAll(".creditBadge").forEach(b=>b.innerText="⚡ Kredin: ?")}})
